Proyecto/Models/Carrito.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Carrito
    {
        public int IDCarrito { get; set; }
        public Nullable<int> IDUsuario { get; set; }
        public Nullable<int> IDProducto { get; set; }
        [Required(ErrorMessage = "El campo {0} es requerido")]
        public Nullable<int> Cantidad { get; set; }
        [Required(ErrorMessage = "El {0} es requerido")]
        [Range(0.01, double.MaxValue, ErrorMessage = "El {0} debe ser mayor que cero")]
        public Nullable<decimal> Total { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}

Proyecto/Controllers/CarritoController.cs
using Proyecto.Interfaces;
using Proyecto.Models;
using Proyecto.Repositories;
using Proyecto.Utilitarios;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;

namespace Proyecto.Controllers
{
    [Authorize]
    public class CarritoController : Controller
    {
        // Acción para mostrar el contenido del carrito

        #region Vistas
        /// <summary>
        /// Acción para mostrar el contenido del carrito del usuario.
        /// </summary>
        /// <returns>Vista que muestra el contenido del carrito.</returns>
        public ActionResult Index()
        {
            try
            {
                // Instancia del repositorio del carrito
                IRepositorioCarrito carrito = new RepositorioCarrito();

                // Obtener el usuario de la sesión
                var user = Session["usuario"] as Usuario;

                // Obtener el ID del usuario
                int idUsuario = user.IDUsuario;

                // Configurar variables para la vista
                ViewBag.idUsuario = idUsuario;
                ViewBag.hascarrito = carrito.ObtenerItemsCarritoPorUsuario(idUsuario).Count() > 0;

                return View();
            }
            catch (Exception ex)
            {
                // Registrar cualquier excepción ocurrida durante el proceso
                Log.Error(ex, MethodBase.GetCurrentMethod());
                // redirigir a la pagina de error en caso de haber un problema
                return RedirectToAction("Error", "Acceso");
            }
        }
        #endregion

        #region Metodo de vista para traduccion del DevExtreme
        /// <summary>
        /// Acción para proporcionar datos de localización para DevExtreme.
        /// </summary>
        /// <returns>Datos de localización para DevExtreme.</returns>
        public ActionResult CldrData()
        {
            return new DevExtreme.AspNet.Mvc.CldrDataScriptBuilder()
                .SetCldrPath("~/Content/cldr-data")
                .SetInitialLocale("es")
                .UseLocales("es", "es")
                .Build();
        }
        #endregion

    }
}

Proyecto/Controllers/PagosController.cs
using ApplicationCore.Utils;
using Microsoft.Reporting.WebForms;
using Newtonsoft.Json;
using Proyecto.Interfaces;
using Proyecto.Models;
using Proyecto.Reportes;
using Proyecto.Reportes.DataSetPedidosTableAdapters;
using Proyecto.Repositories;
using Proyecto.Utilitarios;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.Linq;
using System.Net;
using System.Net.Http.Formatting;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using Utilitarios;

namespace Proyecto.Controllers
{
    [Authorize]
    public class PagosController : Controller
    {
        #region Vistas
        /// <summary>
        /// Acción para mostrar la página de pagos.
        /// </summary>
        /// <returns>
        /// Redirige a la página principal si no hay productos en el carrito;
        /// de lo contrario, muestra la vista de pagos.
        /// </returns>
        public ActionResult Index()
        {
            // Obtener el carrito del usuario
            IRepositorioCarrito carrito = new RepositorioCarrito();

            var user = Session["usuario"] as Usuario;

            int idUsuario = user.IDUsuario;

            int cantidad = carrito.ObtenerItemsCarritoPorUsuario(idUsuario).Count();

            // Redirigir a la página principal si no hay productos en el carrito
            if (cantidad == 0)
            {
                return RedirectToAction("Index", "Home");
            };

            // Mostrar la vista de pagos
            return View();
        }
        #endregion

        #region Acciones

        /// <summary>
        /// Procesa el pago de un pedido utilizando los detalles de una tarjeta de crédito y genera una factura para el usuario.
        /// </summary>
        /// <param name="numeracion">Número de la tarjeta de crédito.</param>
        /// <param name="FechaVencimiento">Fecha de vencimiento de la tarjeta.</param>
        /// <param name="Seguridad">Código de seguridad de la tarjeta.</param>
        /// <returns>ActionResult que indica el resultado del proceso de pago.</returns>
        [HttpPost]
        public ActionResult Cancelar(string numeracion, DateTime FechaVencimiento, int Seguridad)
        {
            try
            {
                var user = Session["usuario"] as Usuario;
                int Idusuario = user.IDUsuario;
                decimal? totalPagar = 0;
                string montototal = "0";
                Tarjeta tarjeta = new Tarjeta()
                {
                    numeracion = numeracion,
                    FechaVencimiento = FechaVencimiento,
                    Seguridad = Seguridad
                };

                // Verificar si el modelo es válido
                if (!ModelState.IsValid)
                {
                    // Retorna un código de estado HTTP de error y un mensaje indicando la falla
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "No se ha podido pagar su pedido");
                }

                // Obtener los elementos en el carrito del usuario
                IRepositorioCarrito carritoCompras = new RepositorioCarrito();
                var lista = carritoCompras.ObtenerItemsCarritoPorUsuario(Idusuario);

                // Crear un pedido para el usuario
                Pedido pedido = new Pedido()
                {
                    IDUsuario = Idusuario,
                    FechaPedido = DateTime.UtcNow,
                    EstadoID = 1
                };

                // Repositorios para manejar pedidos, detalles de pedido y facturas
                IRepositorioPedidos pedidos = new RepositorioPedidos();
                IRepositorioDetallesPedido detalles = new RepositorioDetallesPedido();
                IRepositorioFacturas facturas = new RepositorioFacturas();

                // Realizar un nuevo pedido y obtener su ID
                int idInsertado = pedidos.RealizarPedido(pedido);

                Factura factura = new Factura()
                {
                    IDPedido = idInsertado,
                    FechaFactura = pedido.FechaPedido,
                    DetallesFactura = "Pago con tarjeta"
                };

                // Crear los detalles del pedido
                foreach (var item in lista)
                {
                    DetallePedido detallePedido = new DetallePedido()
                    {
                        IDPedido = idInsertado,
                        IDProducto = item.IDProducto,
                        Cantidad = item.Cantidad,
                        PrecioUnitario = item.Producto.Precio,
                        Subtotal = item.Total
                    };
                    totalPagar += detallePedido.Subtotal;
                    detalles.AgregarDetallePedido(detallePedido);
                }

                // Limpiar el carrito del usuario después de completar la compra
                carritoCompras.EliminarCarritoUsuario(Idusuario);

                // Generar la factura del pedido realizado
                facturas.GenerarFactura(factura);

                // Generar un archivo PDF del reporte del pedido
                byte[] pdfBytes = ReportePedidos(idInsertado);

                if (pdfBytes != null && pdfBytes.Length > 0)
                {
                    //validar si totalpagar tiene algo
                    if (totalPagar.HasValue)
                    {
                        montototal = totalPagar.Value.ToString("#,0.###"); // Aplicando formato
                    }

                    //Estilos del correo
                    string estilos = @"<style>
    body {
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 20px;
      background-color: #f4f4f4;
    }
    .invoice {
      background-color: #fff;
      border-radius: 8px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      padding: 30px;
      max-width: 600px;
      margin: 0 auto;
    }
    .invoice-header {
      text-align: center;
      margin-bottom: 20px;
    }
    .invoice-header h1 {
      font-size: 32px;
      color: #333;
    }
    .invoice-details {
      margin-bottom: 30px;
    }
    .invoice-details p {
      margin: 5px 0;
      color: #555;
    }
    .invoice-total {
      text-align: right;
    }
    .invoice-total p {
      font-weight: bold;
      font-size: 18px;
      margin: 5px 0;
    }
    .thank-you {
      text-align: center;
      margin-top: 20px;
      color: #777;
    }
  </style>";

                    string body = $@"
<!DOCTYPE html>
<html lang=""es"">
<head>
  <meta charset=""UTF-8"">
  <title>Factura de TechStore</title>
  {estilos}
</head>
<body>

<div class=""invoice"">
  <div class=""invoice-header"">
    <h1>Factura de TechStore</h1>
  </div>
  <div class=""invoice-details"">
    <p><strong>Cliente:</strong> {user.Nombre}</p>
    <p><strong>Forma de pago:</strong> {factura.DetallesFactura}</p>
    <p><strong>Fecha:</strong> {factura.FechaFactura.Value.ToLongDateString()}</p>
  </div>

  <div class=""invoice-total"">
    <p><strong>Total:</strong> ₡ {montototal}</p>
  </div>
  <div class=""thank-you"">
    <p>¡Gracias por tu compra!</p>
    <p><strong>Adjuntamos tu factura en pdf junto con este correo</strong></strong></p>
  </div>
</div>
</body>
</html>
";



                    // Enviar el reporte generado por correo electrónico
                    EnviarCorreo enviarCorreo = new EnviarCorreo();
                    enviarCorreo.enviarCorreoGmail(body, user.CorreoElectronico, "Reporte de Pedido", pdfBytes, $"Pedido_{pedido.IDPedido}.pdf");

                    // Mostrar un mensaje de éxito después de enviar el correo
                    TempData["SuccessMessage"] = "Pago procesado exitosamente";
                }
                else
                {
                    // Mostrar un mensaje de error si no se generó el PDF
                    TempData["ErrorMessage"] = "Error al procesar el pago";
                }
                Log.Info($"Se genera el pago para el usuario: {user.Nombre}");
                return View("Index");
            }
            catch (Exception ex)
            {
                // Log para registrar cualquier excepción ocurrida durante el preceso
                Log.Error(ex, MethodBase.GetCurrentMethod());
                return RedirectToAction("Error", "Acceso");
            }
        }
        #endregion

        #region Metodo de vista para traduccion del DevExtreme
        /// <summary>
        /// Método para obtener los datos de localización para DevExtreme.
        /// </summary>
        /// <returns>DevExtreme localization data.</returns>
        public ActionResult CldrData()
        {
            return new DevExtreme.AspNet.Mvc.CldrDataScriptBuilder()
                .SetCldrPath("~/Content/cldr-data")
                .SetInitialLocale("es")
                .UseLocales("es", "es")
                .Build();
        }
        #endregion

        #region Reportes 
        /// <summary>
        /// Método privado para generar el reporte de pedidos en formato PDF.
        /// </summary>
        /// <param name="idpedido">ID del pedido para generar el reporte.</param>
        /// <returns>Bytes del archivo PDF generado.</returns>
        private byte[] ReportePedidos(int idpedido)
        {
            string rptPath = "";
            ReportViewer rv = new ReportViewer();
            byte[] streamBytes = null;
            string mimeType = "";
            string encoding = "";
            string filenameExtension = "";
            string[] streamids = null;
            Warning[] warnings = null;
            string deviceInfo = "";
            ServiceBCCR serviceBCCR = new ServiceBCCR();
            double precioDolar = serviceBCCR.GetMontoVentaHoy();
            try
            {
                

                // Crear un nuevo dataset para los pedidos
                DataSetPedidos dataSetPedidos = new DataSetPedidos();

Proyecto/Views/Carrito/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}





<a href="@Url.Action("Index","Home")" class="btn btn-outline-secondary align-content-center m-2">Regresar</a>

<div class="carrito-container">
    <h2 class="text-center" style="color: #b2b4b2">Carrito de compras</h2>
    @(Html.DevExtreme().DataGrid<Proyecto.Models.Carrito>()
            .ID("gridContainer")
            .DataSource(d => d.WebApi()
        .RouteName("Carritos")
        .LoadAction("Listar")
        .UpdateAction("Actualizar")
        .DeleteAction("Borrar")
        .Key("IDCarrito")
        .OnBeforeSend("beforeSend")
        .OnUpdated("onUpdated")
        .OnRemoved("onRemoving")
        .LoadParams(new { idUsuario = ViewBag.idUsuario }))
            .Paging(p => p.PageSize(10))
            .Pager(p => p
                .ShowPageSizeSelector(true)
                .AllowedPageSizes(new[] { 10, 25, 50, 100 })
            )
            .ShowBorders(true)
            .OnInitialized("onLoading")
            .RepaintChangesOnly(true)
            .Scrolling(s => s.Mode(GridScrollingMode.Virtual))
            .Editing(e => e
                .Mode(GridEditMode.Popup)
                .RefreshMode(GridEditRefreshMode.Reshape)
                .AllowDeleting(true)
                .AllowUpdating(true)
                .UseIcons(true)
                .Form(form => {
                    form.Items(items =>
                    {
                        items.AddSimple().DataField("Producto.NombreProducto");
                        items.AddSimple().DataField("Cantidad");
                    });
                })
            )
            .Columns(columns =>
            {
                columns.AddFor(m => m.Producto.NombreProducto).AllowEditing(false);
                columns.AddFor(m => m.Cantidad).DataType(GridColumnDataType.Number);
                columns.AddFor(m => m.Producto.Precio).AllowEditing(false);
                columns.AddFor(m => m.Total).AllowEditing(false);


            })
            .Summary(s => s.TotalItems(items =>
            {

                items.AddFor(m => m.Total)
                    .SummaryType(SummaryType.Sum)
                    .ValueFormat("#,##0.##");

            }))
       )




</div>



@{if (ViewBag.hascarrito)
    {
        <div class="pagar-container">
            <a class="btn btn-info pagar-btn p-3" href="@Url.Action("Index","Pagos")">Pagar</a>
        </div> }
    else
    {
        <div class="pagar-container">
            <a class="btn btn-info pagar-btn p-3" href="@Url.Action("Index","Home")">Comprar</a>
        </div> }
}






<style>

    .pagar-container {
        display: flex;
        justify-content: flex-end;
        margin-top: 20px;
    }


</style>




<script>


    function onUpdated(e) {
        Swal.fire({
            title: 'Modificacion',
            text: 'Se ha modificado un producto del carrito',
            icon: 'info',
            timerProgressBar: true,
            showConfirmButton: false,
            position: 'center',
            timer: 1500
        });
    }

    function onRemoving(e) {
        Swal.fire({
            title: 'Eliminacion',
            text: 'Se ha Eliminado un Producto del carrito',
            icon: 'warning',
            timerProgressBar: true,
            showConfirmButton: false,
            position: 'center',
            timer: 1500
        });
    }


    function onLoading(e) {
        Swal.fire({
            title: 'Atención',
            text: 'Cargando Carrito',
            icon: 'success',
            timerProgressBar: true,
            showConfirmButton: false,
            position: 'Center',
            timer: 1000
        });
    }

    function beforeSend(operation, ajaxSettings) {
        var data = ajaxSettings.data || {},
            args = Object.keys(data).map(function (key) {
                return key + "=" + data[key];
            }).join(" ");

        var logList = $("#requests ul"),
            time = DevExpress.localization.formatDate(new Date(), "HH:mm:ss"),
            newItem = $("<li>").text([time, ajaxSettings.method, ajaxSettings.url, args].join(" "));

        logList.prepend(newItem);
    }
</script>



<script src="~/Scripts/sweetalert2.js"></script>

<script src="@Url.Action("CldrData", "Carrito", new { t = CldrDataScriptBuilder.GetCacheParam() })"></script>
<script src="~/Scripts/devextreme/localization/dx.messages.es.js"></script>