Proyecto/Controllers/FacturacionController.cs
using DevExtreme.AspNet.Mvc;
using Microsoft.Reporting.WebForms;
using Proyecto.Interfaces;
using Proyecto.Models;
using Proyecto.Permisos;
using Proyecto.Reportes;
using Proyecto.Reportes.DataSetFacturacionTableAdapters;
using Proyecto.Reportes.DataSetReporteMensualTableAdapters;
using Proyecto.Repositories;
using Proyecto.Utilitarios;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;

namespace Proyecto.Controllers
{
    [Authorize]
    public class FacturacionController : Controller
    {

        #region Vistas

        /// <summary>
        /// Acción para mostrar la vista principal de facturación.
        /// </summary>
        /// <returns>Vista principal de facturación.</returns>
        [PermisosRol(RolesPermisos.Empleados, RolesPermisos.Administrador)]
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Acción para mostrar el reporte por fecha.
        /// </summary>
        /// <returns>Vista para generar el reporte por fecha.</returns>
        [PermisosRol(RolesPermisos.Empleados, RolesPermisos.Administrador)]
        public ActionResult ReportePorFecha()
        {
            return View();
        }



        [PermisosRol(RolesPermisos.Administrador)]
        public ActionResult GraficoVentas()
        {
            IRepositorioFacturas facturas = new RepositorioFacturas();
            var lista = facturas.ObtenerFacturas();

            // Suponiendo que tienes una lista de facturas
            DateTime fechaActual = DateTime.Now;
            int mesActual = fechaActual.Month;
            int añoActual = fechaActual.Year;

            // Filtrar las facturas del mes actual
            var facturasMesActual = lista.Where(factura =>
                factura.FechaFactura.Value.Month == mesActual && factura.FechaFactura.Value.Year == añoActual
            );

            // Obtener la cantidad de usuarios únicos
            var cantidadUsuarios = facturasMesActual.Select(factura => factura.Pedido.Usuario.IDUsuario).Distinct().Count();

            // Contar la cantidad total de facturas
            var cantidadFacturas = facturasMesActual.Count();


            ViewBag.CantidadUsuarios = cantidadUsuarios; // Pasar la cantidad de usuarios a la vista
            ViewBag.CantidadFacturas = cantidadFacturas; // Pasar la cantidad de facturas a la vista





            return View();
        }

        #endregion

        #region Metodo de vista para traduccion del DevExtreme
        /// <summary>
        /// Acción para proporcionar datos de localización para DevExtreme.
        /// </summary>
        /// <returns>Datos de localización para DevExtreme.</returns>
        public ActionResult CldrData()
        {
            return new CldrDataScriptBuilder()
                .SetCldrPath("~/Content/cldr-data")
                .SetInitialLocale("es")
                .UseLocales("es", "es")
                .Build();
        }
        #endregion

        #region Acciones de generar reportes
        /// <summary>
        /// Acción para generar el reporte de facturas.
        /// </summary>
        /// <param name="form">Datos del formulario.</param>
        /// <returns>Archivo PDF con el reporte de facturas.</returns>
        [HttpPost]
        public ActionResult ReporteFacturas(FormCollection form)
        {
            // Variables de configuración para el reporte
            string rptPath = "";
            ReportViewer rv = new ReportViewer();
            byte[] streamBytes = null;
            string mimeType = "";
            string encoding = "";
            string filenameExtension = "";
            string[] streamids = null;
            Warning[] warnings = null;
            string deviceInfo = "";
            string fechainicio = "";
            string fechafin = "";

            try
            {
                // Obtener fechas del formulario
                fechainicio = form["txtFiltro1"].ToString();
                fechafin = form["txtFiltro2"].ToString();

                // Verificar si ambas fechas están presentes
                if (string.IsNullOrEmpty(fechainicio) || string.IsNullOrEmpty(fechafin))
                {
                    ViewBag.message = "Los 2 parámetros son requeridos";
                    return View("ReportePorFecha");
                }

                // Acceso a la base de datos para obtener los datos del reporte
                DataSetFacturacion dSFacturacion = new DataSetFacturacion();
                FacturaTableAdapter facturaTable = new FacturaTableAdapter();
                facturaTable.Fill(dSFacturacion.Factura, fechainicio, fechafin);
                rptPath = Server.MapPath("~/Reportes/ReporteFacturacion.rdlc");
                var listaFactura = dSFacturacion.Factura.ToList();

                // Verificar si hay datos para generar el reporte
                if (listaFactura.Count == 0)
                {
                    ViewBag.message = "No existen Facturas en estos lapsos de tiempo";
                    return View("ReportePorFecha");
                }

                // Configuración del reporte y renderización en formato PDF
                ReportDataSource rds = new ReportDataSource("DataSetEncabezadoFactura", listaFactura);
                rv.ProcessingMode = ProcessingMode.Local;
                rv.LocalReport.ReportPath = rptPath;
                rv.LocalReport.DataSources.Add(rds);
                rv.LocalReport.EnableHyperlinks = true;
                rv.LocalReport.Refresh();
                deviceInfo = "<DeviceInfo>" +
                    "  <OutputFormat>PDF</OutputFormat>" +
                    "  <PageWidth>8.5in</PageWidth>" +
                    "  <PageHeight>11in</PageHeight>" +
                    "  <MarginTop>0.5in</MarginTop>" +
                    "  <MarginLeft>1in</MarginLeft>" +
                    "  <MarginRight>1in</MarginRight>" +
                    "  <MarginBottom>0.5in</MarginBottom>" +
                    "  <EmbedFonts>None</EmbedFonts>" +
                    "</DeviceInfo>";
                streamBytes = rv.LocalReport.Render("PDF", deviceInfo, out mimeType, out encoding, out filenameExtension, out streamids, out warnings);
                Log.Info($"Se genera el reporte entre las fechas {fechainicio} y {fechafin} ");
                // Retornar el archivo PDF generado
                return File(streamBytes, "application/pdf");
            }
            catch (Exception ex)
            {
                // Registrar cualquier excepción ocurrida durante el proceso
                Log.Error(ex, MethodBase.GetCurrentMethod());
                // redirigir a la pagina de error en caso de haber un problema
                return RedirectToAction("Error", "Acceso");
            }
        }


        /// <summary>
        /// Acción para generar el reportel mes.
        /// </summary>
        /// <returns>Archivo PDF con el reporte del mes </returns>
        [HttpPost]
        public ActionResult ReporteMensual()
        {
            // Variables de configuración para el reporte
            string rptPath = "";
            ReportViewer rv = new ReportViewer();
            byte[] streamBytes = null;
            string mimeType = "";
            string encoding = "";
            string filenameExtension = "";
            string[] streamids = null;
            Warning[] warnings = null;
            string deviceInfo = "";

            try
            {
                DataSetReporteMensual dSReportemensual = new DataSetReporteMensual();
                UsuarioTableAdapter usuarioTable = new UsuarioTableAdapter();
                CategoriaTableAdapter categoriaTable = new CategoriaTableAdapter();
                RolUsuarioTableAdapter rolUsuarioTable = new RolUsuarioTableAdapter();
                ProductoTableAdapter productoTable = new ProductoTableAdapter();
                EstadoPedidoTableAdapter estadoPedidoTable = new EstadoPedidoTableAdapter();

                usuarioTable.Fill(dSReportemensual.Usuario);
                categoriaTable.Fill(dSReportemensual.Categoria);
                rolUsuarioTable.Fill(dSReportemensual.RolUsuario);
                productoTable.Fill(dSReportemensual.Producto);
                estadoPedidoTable.Fill(dSReportemensual.EstadoPedido);

                var listaUsuarios = dSReportemensual.Usuario.ToList();
                var listaCategoria = dSReportemensual.Categoria.ToList();
                var listaRoles = dSReportemensual.RolUsuario.ToList();
                var listaProducto = dSReportemensual.Producto.ToList();
                var listaEstadoProducto = dSReportemensual.EstadoPedido.ToList();


                rptPath = Server.MapPath("~/Reportes/ReporteMensual.rdlc");

                // Configuración del reporte y renderización en formato PDF
                ReportDataSource rdsUsuario = new ReportDataSource("DataSetMensual", listaUsuarios);
                ReportDataSource rdsCategoria = new ReportDataSource("DataSetCategorias", listaCategoria);
                ReportDataSource rdsRoles = new ReportDataSource("DataSetRoles", listaRoles);
                ReportDataSource rdsProducto = new ReportDataSource("DataSetProducto", listaProducto);
                ReportDataSource rdsEstadoPedido = new ReportDataSource("DataSetEstados", listaEstadoProducto);

                rv.ProcessingMode = ProcessingMode.Local;
                rv.LocalReport.ReportPath = rptPath;
                rv.LocalReport.DataSources.Add(rdsUsuario);
                rv.LocalReport.DataSources.Add(rdsCategoria);
                rv.LocalReport.DataSources.Add(rdsRoles);
                rv.LocalReport.DataSources.Add(rdsProducto);
                rv.LocalReport.DataSources.Add(rdsEstadoPedido);
                rv.LocalReport.EnableHyperlinks = true;
                rv.LocalReport.Refresh();
                deviceInfo = "<DeviceInfo>" +

Proyecto/Views/Facturacion/GraficoVentas.cshtml
@{
    ViewBag.Title = "GraficoVentas";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<div class="container mt-4 mb-4 d-flex justify-content-center align-items-center flex-column">
    <div class="alert" role="alert">
        <h4 class="text-center text-white" style="font-size: 2rem">Reporte mensual</h4>
    </div>
    <button id="descargarReporteBtn" class="btn btn-primary btn-block" style="font-size:2rem">
        <i class="dx-icon-inf"></i> Descargar Reporte
    </button>
</div>


<div id="chartUsuariosFacturas"></div>


@section scripts {
    <script>
        // Gráfico de pastel (Cantidad de Usuarios y Facturas)
        var cantidadUsuarios = @ViewBag.CantidadUsuarios;
        var cantidadFacturas = @ViewBag.CantidadFacturas;

        var dataSource = [
            { estado: "Usuarios", cantidad: cantidadUsuarios },
            { estado: "Facturas", cantidad: cantidadFacturas }
        ];

        $("#chartUsuariosFacturas").dxPieChart({
            dataSource: dataSource,
            series: {
                argumentField: "estado",
                valueField: "cantidad",
                label: {
                    visible: true,
                    connector: {
                        visible: true
                    }
                }
            },
            title: "Cantidad de Usuarios y Facturas en el Mes",
            legend: {
                horizontalAlignment: "center",
                verticalAlignment: "bottom"
            },
            export: {
                enabled: true,
                formats: ["PNG", "JPEG", "SVG", "PDF"]
            }
        });
        //fin del grafico pastel



        // Agregar evento clic al botón
        document.getElementById('descargarReporteBtn').addEventListener('click', function() {
            // Realizar la petición al controlador para descargar el reporte
            fetch('@Url.Action("ReporteMensual", "Facturacion")', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json' // Ajusta si es necesario
                }
            })
            .then(response => response.blob())
            .then(blob => {
                // Crear un enlace para descargar el archivo y simular clic para descargarlo
                const url = window.URL.createObjectURL(new Blob([blob]));
                const link = document.createElement('a');
                link.href = url;
                link.setAttribute('download', 'reporte_mensual.pdf');
                document.body.appendChild(link);
                link.click();
                link.parentNode.removeChild(link);
            })
            .catch(error => {
                console.error('Error al descargar el reporte:', error);
            });
        });




    </script>
}

Proyecto/Views/Facturacion/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="text-white text-center">Facturacion</h2>
@(Html.DevExtreme().DataGrid<Proyecto.Models.Factura>()
    .ID("gridContainer")
    .DataSource(d => d.WebApi()
    .RouteName("Factura")
    .LoadAction("Listar")
    .Key("IDFactura")
    .OnBeforeSend("beforeSend")
    )
    .ShowBorders(true)
    .OnInitialized("onLoading")
    .RepaintChangesOnly(true)
    .Paging(p => p.PageSize(5))
    .Pager(pager =>
    {
        pager.Visible(true);
        pager.ShowPageSizeSelector(true);
        pager.AllowedPageSizes(new JS("[5, 10, 25, 50, 'all']"));
        pager.ShowInfo(true);
        pager.ShowNavigationButtons(true);
    })
    .FilterRow(f => f.Visible(true))
    .SearchPanel(searchPanel => searchPanel.Visible(true))
    .ColumnHidingEnabled(true)
    .HeaderFilter(f => f.Visible(true))
    .GroupPanel(p => p.Visible(true))
    .Grouping(g => g.AutoExpandAll(false))
    .RemoteOperations(true)
    //.Scrolling(s => s.Mode(GridScrollingMode.Virtual))
    .Editing(e => e
    .Mode(GridEditMode.Popup)
    .RefreshMode(GridEditRefreshMode.Reshape)
    .UseIcons(true)
    )
    .Columns(columns =>
    {
        columns.AddFor(m => m.IDFactura).Caption("Nº factura").Alignment(HorizontalAlignment.Center);
        columns.AddFor(m => m.FechaFactura).Caption("Fecha de Factura").Alignment(HorizontalAlignment.Center);
        columns.AddFor(m => m.DetallesFactura).Caption("Detalle").Alignment(HorizontalAlignment.Center);
        columns.AddFor(m => m.Pedido.Usuario.Nombre).Caption("Usuario").Alignment(HorizontalAlignment.Center);
    })
    .Export(e => e.Enabled(true).AllowExportSelectedData(true))
    .OnExporting("exportToPDF")
    .Selection(s => s.Mode(SelectionMode.Multiple))
    .MasterDetail(md => {
    md.Enabled(true);
    md.Template(@<text>
            <div class="master-detail-caption">Detalle de la factura <%- data.IDFactura %> del Usuario <%- data.Pedido.Usuario.Nombre %></div>
            @(Html.DevExtreme().DataGrid<Proyecto.Models.Pedido>()
                .ColumnAutoWidth(true)
                .ShowBorders(true)
                .Columns(columns => {
                    columns.AddFor(m => m.IDPedido).Alignment(HorizontalAlignment.Center);
                    columns.AddFor(m => m.EstadoPedido.Detalle).Caption("Estado del Pedido").Alignment(HorizontalAlignment.Center);

                })
                .DataSource(d => d.WebApi()
                    .RouteName("Pedidos")
                    .LoadAction("Listarporusuario")
                    .LoadParams(new { idUsuario = new JS("data.Pedido.Usuario.IDUsuario") })
                )
            )
        </text>);
    })


    )





<script>

    function onLoading(e) {
        Swal.fire({
            title: 'Atención',
            text: 'Cargando Facturas',
            icon: 'success',
            timerProgressBar: true,
            showConfirmButton: false,
            position: 'Center',
            timer: 1000
        });
    }

    function beforeSend(operation, ajaxSettings) {
        var data = ajaxSettings.data || {},
            args = Object.keys(data).map(function (key) {
                return key + "=" + data[key];
            }).join(" ");

        var logList = $("#requests ul"),
            time = DevExpress.localization.formatDate(new Date(), "HH:mm:ss"),
            newItem = $("<li>").text([time, ajaxSettings.method, ajaxSettings.url, args].join(" "));

        logList.prepend(newItem);
    }
</script>




<script>
    function exportToPDF() {
        var doc = new jsPDF();
        var dataGrid = $("#gridContainer").dxDataGrid("instance");
        DevExpress.pdfExporter.exportDataGrid({
            jsPDFDocument: doc,
            component: dataGrid
        }).then(function () {
            doc.save("Facturas.pdf");
        });
    }
</script>


@* Script requeridos para exportar a PDF*@
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.3.1/jspdf.umd.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.5.14/jspdf.plugin.autotable.min.js"></script>
<script>
    window.jsPDF = window.jspdf.jsPDF;
    applyPlugin(window.jsPDF);
</script>




<script src="~/Scripts/sweetalert2.js"></script>

<script src="@Url.Action("CldrData", "Facturacion", new { t = CldrDataScriptBuilder.GetCacheParam() })"></script>
<script src="~/Scripts/devextreme/localization/dx.messages.es.js"></script>

Proyecto/Views/Facturacion/ReportePorFecha.cshtml
@{
    ViewBag.Title = "ReportePorFecha";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="text-white text-center">Reporte Por Fecha</h2>


@if (ViewBag.message != null)
{
    <h1 class="text-danger text-center">@ViewBag.message</h1>
}

@using (Html.BeginForm("ReporteFacturas", "Facturacion", FormMethod.Post, new { target = "_blank", onsubmit = "return validateForm();" }))
{

    <div class="container">
        <div class="row d-flex justify-content-center align-items-center">
            <div class="col-sm-3">
                <div class="text-center">
                    <!-- Centrar el texto -->
                    <span class="text-white">Fecha inicio</span>
                </div>
                <div class="h-25">
                    @(Html.DevExtreme().
                   Calendar().Min(DateTime.Now.AddMonths(-3)).Max(DateTime.Now)
                   .ID("txtFiltro1")
                   .Name("txtFiltro1"))
                </div>
            </div>

            <div class="ml-5 col-sm-3">
                <div class="text-center">
                    <!-- Centrar el texto -->
                    <span class="text-white">Fecha Fin</span>
                </div>
                <div class="h-25">
                    @(Html.DevExtreme().
                   Calendar().Min(DateTime.Now.AddMonths(-3)).Max(DateTime.Now)
                   .ID("txtFiltro2")
                   .Name("txtFiltro2"))
                </div>
            </div>
        </div>
        <div class="row text-right text-white">
            <div class="col-sm h-25">
                @(Html.DevExtreme().
                Button().
                Text("Consultar").
                UseSubmitBehavior(true).
                Type(ButtonType.Success))
            </div>
        </div>
    </div>
    <br>

}



<script type="text/javascript">

    function validateForm() {
        var input = $('#txtFiltro1').dxTextBox('instance').option('value');
        var input2 = $('#txtFiltro2').dxTextBox('instance').option('value');
        if (input == "" || input2 == "") {
            return false;
        } else {

            return true;
        }
    }

</script>